// Re-export commonly used Heroicons with better names
export {
  HomeIcon,
  UserIcon,
  BriefcaseIcon,
  EnvelopeIcon,
  Bars3Icon,
  XMarkIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ArrowTopRightOnSquareIcon,
  EyeIcon,
  CodeBracketIcon,
  DevicePhoneMobileIcon,
  ComputerDesktopIcon,
  ServerIcon,
  GlobeAltIcon,
  SunIcon,
  MoonIcon,
  SparklesIcon,
  RocketLaunchIcon,
  LightBulbIcon,
  AcademicCapIcon,
  BuildingOffice2Icon,
  CalendarDaysIcon,
  MapPinIcon,
  PhoneIcon,
  InboxIcon,
  DocumentIcon,
  LinkIcon,
  StarIcon,
  HeartIcon,
  ShareIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  PlusIcon,
  MinusIcon,
  CheckIcon,
  ExclamationCircleIcon,
  InformationCircleIcon,
  CheckCircleIcon,
  XCircleIcon,
} from '@heroicons/react/24/outline';

export {
  HomeIcon as HomeIconSolid,
  UserIcon as UserIconSolid,
  BriefcaseIcon as BriefcaseIconSolid,
  EnvelopeIcon as EnvelopeIconSolid,
  StarIcon as StarIconSolid,
  HeartIcon as HeartIconSolid,
  CheckCircleIcon as CheckCircleIconSolid,
  ExclamationCircleIcon as ExclamationCircleIconSolid,
  InformationCircleIcon as InformationCircleIconSolid,
  XCircleIcon as XCircleIconSolid,
} from '@heroicons/react/24/solid';